### ISSUE TITLE
Migration to MTE 5.9.0

### ISSUE THREAD

**Issue by Niklp09** [Archtec-io/bugtracker#201]
#### Deprecated stuff that needs to be addressed
- [x] API change in set_physics_override #179 
- [x] Nodebox and mesh nodes now require use_texture_alpha to render with transparency #137 
- [ ] `hud_elem_type` was renamed to `type` (replaced the most annoying ones. will be done over time)
- [x] Mod directories are read only now - was never used here AFAIK

#### Actual upgrade
- [x] Add 5.9.0 to CI test matrix https://github.com/Archtec-io/archtec-mods/commit/6c94b8f371d8e60a18a3f591347245d98f11d908
- [x] Re-enable invsaw (inv bugs fixed in 5.9) #145 

Player info debug patch https://raw.githubusercontent.com/minetest-hosting/minetest-docker/c15e5aa5150a014c3a8bb3dfa1da41c67220a386/patches/player_debug_info.patch

**Comment by Niklp09** [comment]
New(?) deprecation warning after update
```lua
Deprecated call to `minetest.show_formspec`:`formname` must not be empty (at ...inetest-5.9.0/bin/../mods/travelnet/formspecs-legacy.lua:101)
```
