### ISSUE TITLE
roadmap Nov + Dec 22

### ISSUE THREAD

**Issue by Niklp09** [Archtec-io/bugtracker#22]
- [x] remove monoids mod
- [x] optimize `get_connected_players` calls
- [x] switch to builtin hudbars
- [x] redo darkage mapgen
- [x] redo item_drop
...
